import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ドラえもんはここにいるよ～',
  description: 'Generated by create next app',
  icons: {
    icon: '../public/doraemon-icon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <link rel="icon" href="../public/doraemon-icon.png" />
    </html>
  );
}
